# /etc/conf.d/emacs: config file for /etc/init.d/emacs.<user>
# This can also be used as multiplexed configuration, i.e. runscript
# looks for both /etc/conf.d/emacs and /etc/conf.d/emacs.<user>.

# Absolute path to the Emacs binary
#EMACS="/usr/bin/emacs"

# Emacs detaches and exits the parent process only after loading the
# user's .emacs (initialisation). Anything may happen there, so we use
# a wrapper script to ensure that the Emacs daemon properly starts.
# This also executes a login shell to read the user's profile.
#EMACS_START="/usr/libexec/emacs/emacs-wrapper.sh"

# Timeout to wait for the daemon to detach
#EMACS_TIMEOUT=15

# Any additional options to pass to emacs --daemon
#EMACS_OPTS=""
