# /etc/conf.d/emacs: config file for /etc/init.d/emacs.<user>
# This can also be used as multiplexed configuration, i.e. runscript
# looks for both /etc/conf.d/emacs and /etc/conf.d/emacs.<user>.

# Absolute path to the Emacs binary
#EMACS="/usr/bin/emacs"

# You may specify a wrapper script for starting. An example that
# just sources the user's profile before starting Emacs is in
# /usr/libexec/emacs/emacs-wrapper.sh.
# Default is to start Emacs directly.
#EMACS_START=""

# Any additional options to pass to emacs --daemon
#EMACS_OPTS=""
