.\" Copyright 2008 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2
.\" $Id: $
.\"
.TH "emacs-updater" 8 "November 2008" "Gentoo Linux"
.SH NAME
emacs-updater \- rebuild Emacs packages
.SH SYNOPSIS
.BI "emacs-updater" " [OPTION]..."
.SH DESCRIPTION
Find packages that are installed in the wrong location or rebuild all
GNU Emacs packages.
.SH OPTIONS
.TP
.BI "-a, --action" " ACTION[,ACTION]..."
Specify actions, comma-separated list of:

.IR sitedir :
Find site-init files not in the new-style location

.IR rebuild :
Rebuild packages with Elisp files byte-compiled by a different Emacs version

.IR all :
Rebuild all packages that have byte-compiled Elisp files

.RI "(default: " sitedir ", " rebuild ")"
.TP
.B "-e, --exact"
Match exact versions when remerging packages
.TP
.B "-n, --nocolour"
Disable colour in output
.TP
.B "-p, --pretend"
Don't actually emerge packages
.TP
.BI "-P, --package-manager" " PM"
Select a package manager.
.IR PM " is one out of " portage " (default), " pkgcore ", or " paludis
.TP
.B "-h, --help"
Display help and exit
.SH AUTHORS
Christian Faulhammer <fauli@gentoo.org>
.br
Ulrich Mueller <ulm@gentoo.org>
.SH "SEE ALSO"
.BR emacs (1),
.BR qfile (1)
