#!/bin/bash

# Copyright 2007-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

# Authors:
# Christian Faulhammer <opfer@gentoo.org>
# Ulrich Mueller <ulm@gentoo.org>

VERSION=0.7
SITELISP=/usr/share/emacs/site-lisp
TMPFILE="$(mktemp /tmp/emacs-updater.XXXXXX)"
SORTFILE="$(mktemp /tmp/emacs-updater.XXXXXX)"
ACTIONS=

cat <<-EOF

Emacs updater version ${VERSION}
Written by the Gentoo Emacs team http://www.gentoo.org/proj/en/lisp/emacs/
Find packages that are installed in the wrong location or rebuild all
GNU Emacs packages

EOF

usage() {
    sed -e 's/^X//' <<-EOF
	Usage: ${0##*/} [OPTION]...
	X  -n, --nocolour         disable colour in output
	X  -p, --pretend          don't actually emerge packages
	X  -h, --help             display this help and exit
	X  -a, --action <arg>     arg is one out of
	X                         'obsolete_location': find site-files not
	X                           in the new-style location
	X                         'rebuild': rebuild packages with Elisp files
	X                           byte-compiled by a different Emacs version
	X                         'rebuild_all': rebuild all packages that have
	X                           byte-compiled Elisp files
	EOF
    exit ${1}
}

# Read in all command-line options and force English output
OPTIONS=$(LC_ALL=C getopt -o hpna: --long help,pretend,nocolour,action: \
     -n 'emacs-updater' -- "$@")
[ $? -eq 0 ] || usage 1

eval set -- "${OPTIONS}"

while true
do
    case "${1}" in
	-h|--help)      usage 0 ;;
	-p|--pretend)   PRETEND="true"; shift 1 ;;
	-n|--nocolour)  NOCOLOUR="true"; shift 1 ;;
	-a|--action)
	    case "${2}" in
		obsolete_location | rebuild | rebuild_all)
		    ACTIONS="${ACTIONS} ${2}"
		    ;;
		*)
		    echo "Invalid action given!"
		    exit 20
		    ;;
    	    esac
	    shift 2
	    ;;

	--) shift; break ;;
    esac
done

# Default action if the user did not specify it
ACTIONS=${ACTIONS:-obsolete_location}

# Only set colours if output is not redirected or the --no-colour
# option is not set
if [ -t 1 ] && [ -z "${NOCOLOUR}" ] ; then
    RED=$(tput -S <<<$'setaf 1\nbold')
    GREEN=$(tput -S <<<$'setaf 2\nbold')
    YELLOW=$(tput -S <<<$'setaf 3\nbold')
    BLUE=$(tput -S <<<$'setaf 4\nbold')
    MAGENTA=$(tput -S <<<$'setaf 5\nbold')
    CYAN=$(tput -S <<<$'setaf 6\nbold')
    BOLD=$(tput bold)
    NORMAL=$(tput sgr0)
fi

# Some type of output can be prettified and capsulated in functions
message() {
    local OUTPUT=$@
    echo "${GREEN}*${NORMAL}${BOLD} ${OUTPUT}${NORMAL}"
}

warning() {
    local OUTPUT=$@
    echo "${YELLOW}*${NORMAL}${BOLD} ${OUTPUT}${NORMAL}"
}

failure() {
    local OUTPUT=$@
    echo "${RED}*${NORMAL}${BOLD} ${OUTPUT}${NORMAL}" 
}

if ! [ -x /usr/bin/emacs ]; then
    echo
    failure "Please emerge virtual/emacs to use this tool"
    exit 2
fi

if ! [ -x /usr/bin/qfile ]; then
    echo
    failure "Please emerge app-portage/portage-utils to use this tool"
    exit 2
fi

emacs-version() {
    /usr/bin/emacs -batch -q --no-site-file --eval "(princ emacs-version)" \
	|| { failure "Cannot run Emacs"; exit 5; }
}

obsolete_location() {
    local sf
    for sf in "${ROOT}${SITELISP}"/[0-9][0-9]*-gentoo.el
    do
	[ "${sf##*/}" = 00site-gentoo.el ] && continue
	message "Processing ${sf##*/} ..."
	qfile -qCR "${sf}" >> "${TMPFILE}"
    done
}

rebuild() {
    local active version elc
    active=$(emacs-version)
    [ -n "${active}" ] || { failure "Cannot determine Emacs version"; exit 6; }
    message "Currently selected GNU Emacs version: ${active}"

    for elc in $(find ${SITELISP} -name *.elc)
    do
	version=$(sed -n \
	    '/^[^;]/q;s/\.$//;s/.*emacs version \([0-9].*\)/\1/Ip' ${elc})
	version=${version:-undefined}

	if [ "${version}" != "${active}" ] || [ "${1}" = all ]; then
	    message "Processing ${elc##*/}" \
		"(compiled by Emacs version ${version}) ..."
	    qfile -qCR "${elc}" >> "${TMPFILE}"
	else
	    message "Skipping ${elc##*/}" \
		"(compiled by Emacs version ${version})"
	fi
    done
}

rebuild_all() {
    rebuild all
}

cleanup() {
    rm -f "${TMPFILE}" "${SORTFILE}"
}

trap cleanup EXIT

for action in ${ACTIONS}; do
    ${action}
done

echo
if [ ! -s "${TMPFILE}" ]; then
    warning "No packages to update, quitting."
    exit 3
fi

sort -u "${TMPFILE}" > "${SORTFILE}"
mv "${SORTFILE}" "${TMPFILE}"

NO_OF_PACKAGES=$(sed -n '$=' "${TMPFILE}")

[ ${NO_OF_PACKAGES} -eq 1 ] && s= || s=s
message "${NO_OF_PACKAGES} package${s} to remerge:"

echo
cat "${TMPFILE}"

if [ "${PRETEND}" ]; then
    exit 4
fi

echo
echo -n "${BOLD}Remerge packages?${NORMAL} [${GREEN}Yes${NORMAL}/${RED}No${NORMAL}] "
read choice
echo
case "${choice}" in
    y*|Y*|"")
	;;
    *)
	warning "Quitting."
	exit 10 ;;
esac

emerge --oneshot --ask --verbose $(cat "${TMPFILE}")

warning "If a package is being rebuilt over and over again,"
warning "please report it on http://bugs.gentoo.org/"
