.\" -*- coding: utf-8 -*-
.\" Copyright 2008-2014 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2 or later
.\"
.TH emacs-updater 8 "May 2014" "Gentoo Linux"
.SH NAME
emacs-updater \- rebuild Emacs packages
.SH SYNOPSIS
.B emacs-updater
.I [OPTION]...
.SH DESCRIPTION
Find packages that are installed in the wrong location or rebuild all
GNU Emacs packages.
.SH OPTIONS
.TP
.BI "-a, --action=" ACTION[,ACTION]...
Specify actions, comma-separated list of:

.BR sitedir :
Find site-init files not in the new-style location.

.BR rebuild :
Rebuild packages with Elisp files byte-compiled by a different Emacs
version.

.BR all :
Rebuild all packages that have byte-compiled Elisp files.

(default:
.BR sitedir ,
.BR rebuild )
.TP
.B -b, --batch
Batch mode, don't ask the user any questions.
.TP
.BI \-\-color "[=MODE], " \-\-colour [=MODE]
Enable or disable colour output.
.I MODE
can be
.BR yes ,
.BR no ,
or
.BR auto .
The default is
.BR auto ,
for which colour output is enabled only if standard output is
connected to a terminal.
.TP
.B -e, --exact
Match exact versions when remerging packages.
.TP
.B -m, --major
Use only the major version when comparing Emacs version numbers.
.TP
.B -o, --orphans
List orphan files, i.e. files that are not owned by any package.
Implies
.BR --action=all .
.TP
.B -p, --pretend
Don't actually emerge packages.
.TP
.BI "-P, --package-manager=" PM
Select a package manager.
.I PM
is one out of
.BR portage ,
.BR pkgcore ,
or
.BR paludis .
If the argument
.B auto
is given, then the package manager is automatically determined.
This is the default.
.TP
.BI --package-manager-command= CMD
Call
.I CMD
instead of the default package manager command.
.I CMD
may include options in which case the whole command string must be
passed as a single argument (i.e. included in quotes).
.TP
.B -h, --help
Display help and exit.
.TP
.B --version
Output version information and exit.
.TP
.BI -- " OPTION..."
Pass additional options to package manager.  This must be last on the
command line.
.SH ENVIRONMENT
.TP
.B PACKAGE_MANAGER
The preferred package manager.  The same values as for the
.B -P
option are allowed.
.SH AUTHORS
Christian Faulhammer <fauli@gentoo.org>
.br
Ulrich Müller <ulm@gentoo.org>
.SH SEE ALSO
.BR emacs (1),
.BR qfile (1)
