# /etc/conf.d/emacs: config file for /etc/init.d/emacs.<user>
# This can also be used as multiplexed configuration, i.e. openrc-run
# looks for both /etc/conf.d/emacs and /etc/conf.d/emacs.<user>.

# Absolute path to the emacs binary
#EMACS="/usr/bin/emacs"

# Options to pass to emacs. Don't remove "--fg-daemon".
#EMACS_OPTS="--fg-daemon"

# Wrapper script for starting Emacs. This executes a login shell,
# in order to read the user's profile. #246460
#EMACS_START="/usr/libexec/emacs/emacs-wrapper.sh"

# Optionally, you may execute a custom script before stopping the
# daemon. #246462
#EMACS_STOP=""

# Timeout (in seconds) to wait for termination of the daemon
#EMACS_TIMEOUT="30"

# The SHELL variable to be passed to EMACS_START. emacs-wrapper.sh uses
# this as the user's login shell. If (explicitly set to) empty, then
# the shell field from the passwd file is used.
#EMACS_SHELL="/bin/bash"
