;;; site-gentoo.el --- Gentoo site initialisation  -*-lexical-binding:t-*-

;;; Commentary:
;; Automatically generated by elisp-common.eclass
;; DO NOT EDIT THIS FILE

;;; Code:


(provide 'site-gentoo)

;; Local Variables:
;; no-byte-compile: t
;; buffer-read-only: t
;; End:

;;; site-gentoo.el ends here
